//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./bot_types');
//HELPER FUNCTIONS AND STRUCTURES

Publish_save_args = function(args) {
  this.Qt = null;
  if (args) {
    if (args.Qt !== undefined && args.Qt !== null) {
      this.Qt = new ttypes.Question(args.Qt);
    }
  }
};
Publish_save_args.prototype = {};
Publish_save_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.Qt = new ttypes.Question();
        this.Qt.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Publish_save_args.prototype.write = function(output) {
  output.writeStructBegin('Publish_save_args');
  if (this.Qt !== null && this.Qt !== undefined) {
    output.writeFieldBegin('Qt', Thrift.Type.STRUCT, 1);
    this.Qt.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Publish_save_result = function(args) {
};
Publish_save_result.prototype = {};
Publish_save_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Publish_save_result.prototype.write = function(output) {
  output.writeStructBegin('Publish_save_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

PublishClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
PublishClient.prototype = {};
PublishClient.prototype.seqid = function() { return this._seqid; }
PublishClient.prototype.new_seqid = function() { return this._seqid += 1; }
PublishClient.prototype.save = function(Qt, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_save(Qt);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_save(Qt);
  }
};

PublishClient.prototype.send_save = function(Qt) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('save', Thrift.MessageType.CALL, this.seqid());
  var args = new Publish_save_args();
  args.Qt = Qt;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PublishClient.prototype.recv_save = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Publish_save_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
PublishProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
PublishProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

PublishProcessor.prototype.process_save = function(seqid, input, output) {
  var args = new Publish_save_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.save.length === 1) {
    Q.fcall(this._handler.save, args.Qt)
      .then(function(result) {
        var result = new Publish_save_result({success: result});
        output.writeMessageBegin("save", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("save", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.save(args.Qt, function (err, result) {
      if (err == null) {
        var result = new Publish_save_result((err != null ? err : {success: result}));
        output.writeMessageBegin("save", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("save", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

